version: '3.1'

services:
  springboot:
    image: ms_elq_resource_server:latest
    build: .
    restart: always
    container_name: mselq_resource_server
    env_file:
      - $HOME/dockerfiles/config/.env
    extra_hosts:
      - localhost:${LOCAL_IP}
    environment:
      - DATABASE_URL=postgres://postgres:postgresql1@localhost:5432/myschema
    ports:
      - 8085:8085
    depends_on:
      - mongo_mselq_server
  
  mongo_mselq_server:
    image: mongo:latest
    container_name: mongo_mselq_server
    ports:  # for demo/debug purpose only
       - 27017:27017
    volumes:
      - $HOME/mongodb_data/docker_data:/mongodb_data/docker_data
    restart: always

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongo_mselq_server
    ports:
      - 3300:3000

