language: java

sudo: false
script: mvn clean compile

jdk:
  - oraclejdk8

script:
  - mvn clean test org.jacoco:jacoco-maven-plugin:report-aggregate

after_success:
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report
